// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVtAylMKj5rGxGtN-Jw_NjBu-8BV6Ym3I',
    appId: '1:300337635091:web:846d68644dc0b93fb984e6',
    messagingSenderId: '300337635091',
    projectId: 'loan-manager-6257e',
    authDomain: 'loan-manager-6257e.firebaseapp.com',
    storageBucket: 'loan-manager-6257e.appspot.com',
    measurementId: 'G-HX0KTD6XNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVD-bWhzgRG3Gvajv4GW_mMzS9LkWFHjY',
    appId: '1:300337635091:android:e32c231fe9c5c329b984e6',
    messagingSenderId: '300337635091',
    projectId: 'loan-manager-6257e',
    storageBucket: 'loan-manager-6257e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4q1nNrbph_YtPO62uz29iUcDtOEgDY5E',
    appId: '1:300337635091:ios:389a046f4bb7e66cb984e6',
    messagingSenderId: '300337635091',
    projectId: 'loan-manager-6257e',
    storageBucket: 'loan-manager-6257e.appspot.com',
    iosBundleId: 'com.example.loanManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4q1nNrbph_YtPO62uz29iUcDtOEgDY5E',
    appId: '1:300337635091:ios:de22bca776dc347db984e6',
    messagingSenderId: '300337635091',
    projectId: 'loan-manager-6257e',
    storageBucket: 'loan-manager-6257e.appspot.com',
    iosBundleId: 'com.example.loanManager.RunnerTests',
  );
}
